---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: service-two-db-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/service-two-db/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: service-two-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Secret
metadata:
  name: service-two-db-secret
type: Opaque
data:
  root_pass: cm9vdDEyMw==
  mysql_user: c2VydmljZS10d28=
  mysql_pass: c2VydmljZS10d28=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: service-two-db-configmap
data:
  mysql_database: service-two


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicetwodb
spec:
  replicas: 1
  selector:
    matchLabels:
      db: servicetwodb
  template:
    metadata:
      labels:
        db: servicetwodb
    spec:
      containers:
      - name: servicetwodb
        image: mysql/mysql-server:8.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: service-two-db-secret
              key: root_pass
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: service-two-db-configmap
              key: mysql_database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: service-two-db-secret
              key: mysql_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: service-two-db-secret
              key: mysql_pass
        volumeMounts:
        - name: service-two-db-persistent-storage
          mountPath: /var/lib/mysql
      
      volumes:
      - name: service-two-db-persistent-storage
        persistentVolumeClaim:
          claimName: service-two-db-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: service-two-db
spec:
  selector:
    db: servicetwodb
  ports:
  - port: 3306
    targetPort: 3306
